DROP DATABASE `examdb`;
CREATE DATABASE `examdb`;
GRANT ALL PRIVILEGES ON `examdb`.* TO 'bvthanghoa'@'*.*' IDENTIFIED BY '57PhanKeBinh';
FLUSH PRIVILEGES;
USE `examdb`;
CREATE TABLE `Patient`(
    `PatientId` INT(10) UNSIGNED PRIMARY NOT NULL,
    `AdminissionId` INT(10) UNSIGNED NOT NULL,
    `DepartmentId` SMALLINT(6) NOT NULL,
    `EmrId` INT(10) UNSIGNED NOT NULL UNIQUE COMMENT 'Mã bệnh án'
    
);
-- ALTER TABLE
--     `Patient` ADD UNIQUE `emradmission_adminissionid_patientid_unique`(`AdminissionId`, `PatientId`);
-- ALTER TABLE
--     `Patient` ADD INDEX `emradmission_patientid_index`(`PatientId`);
-- ALTER TABLE
--     `Patient` ADD INDEX `emradmission_adminissionid_index`(`AdminissionId`);
-- ALTER TABLE
--     `Patient` ADD INDEX `emradmission_departmentid_index`(`DepartmentId`);
-- ALTER TABLE
--     `Patient` ADD UNIQUE `emradmission_emrid_unique`(`EmrId`);

-- CREATE TABLE `EmrSample`(
--     `EmrSampleId` SMALLINT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     `EmrSampleName` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL'
-- );
-- CREATE TABLE `ListDepartment`(
--     `DepartmentId` SMALLINT(6) NOT NULL,
--     `DepartmentName` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL',
--     PRIMARY KEY(`DepartmentId`)
-- );
-- CREATE TABLE `ListDrug`(
--     `id` SMALLINT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     `DrugId` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL',
--     `DrugName` VARCHAR(255) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Ten biet duoc',
--     `DrugChemical` VARCHAR(255) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Ten hoa chat',
--     `DrugContent` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Ham luong',
--     `DrugFormulation` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Dang bao che',
--     `DrugRemains` SMALLINT(6) NULL DEFAULT 'DEFAULT NULL' COMMENT 'S\\u1ed1 l\\u01b0\\u1ee3ng t\\u1ed3n',
--     `DrugGroup` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL',
--     `DrugTherapy` VARCHAR(200) NULL DEFAULT 'DEFAULT NULL',
--     `DrugRoute` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL',
--     `Count` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL',
--     `CountStr` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL'
-- );
-- ALTER TABLE
--     `ListDrug` ADD UNIQUE `listdrug_drugid_unique`(`DrugId`);
-- ALTER TABLE
--     `ListDrug` ADD INDEX `listdrug_druggroup_index`(`DrugGroup`);
-- CREATE TABLE `ListProcedure`(
--     `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     `ProcedureId` VARCHAR(50) NOT NULL,
--     `ProcedureDesc` VARCHAR(100) NOT NULL COMMENT 'X quang c\\u1eb3ng tay...',
--     `ProcedureGroup` VARCHAR(100) NOT NULL,
--     `ProcedureBHYT` TINYINT(1) NOT NULL DEFAULT '1',
--     `ProcedurePriceBHYT` INT(10) UNSIGNED NOT NULL,
--     `ProcedurePriceVP` INT(10) UNSIGNED NOT NULL
-- );
-- ALTER TABLE
--     `ListProcedure` ADD UNIQUE `listprocedure_procedureid_unique`(`ProcedureId`);
-- CREATE TABLE `ListSign`(
--     `id` SMALLINT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     `EmrSampleId` SMALLINT(6) NULL DEFAULT 'DEFAULT NULL' COMMENT 'M\\0e3 m\\u1eabu b\\u1ec7nh \\0e1n',
--     `SignId` SMALLINT(6) NULL DEFAULT 'DEFAULT NULL',
--     `SignDesc` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL' COMMENT 'M\\0f4 t\\u1ea3: Kh\\0f3 th\\u1edf...',
--     `SignDefault` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL' COMMENT 'M\\u1eb7c \\u0111\\u1ecbnh: B\\0ecnh th\\u01b0\\u1eddng...',
--     `SubSystemId` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL' COMMENT 'C\\u01a1 quan: Ph\\u1ed5i...'
-- );
-- ALTER TABLE
--     `ListSign` ADD UNIQUE `listsign_emrsampleid_signid_unique`(`EmrSampleId`, `SignId`);
-- ALTER TABLE
--     `ListSign` ADD INDEX `listsign_emrsampleid_index`(`EmrSampleId`);
-- ALTER TABLE
--     `ListSign` ADD UNIQUE `listsign_signid_unique`(`SignId`);
-- CREATE TABLE `ListStaff`(
--     `StaffId` SMALLINT(6) NOT NULL,
--     `StaffName` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL',
--     `StaffRole` ENUM(
--         'B\0e1c s\u0129',
--         '\u0110i\u1ec1u d\u01b0\u1ee1ng',
--         'K\u1ef9 thu\u1eadt vi\0ean',
--         'Kh\0e1c'
--     ) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Vai tr\\0f2: B\\0e1c s\\u0129...',
--     `DerpartmentId` SMALLINT(6) NULL DEFAULT 'DEFAULT NULL',
--     PRIMARY KEY(`StaffId`)
-- );
-- ALTER TABLE
--     `ListStaff` ADD INDEX `liststaff_derpartmentid_index`(`DerpartmentId`);
-- CREATE TABLE `ListTest`(
--     `id` SMALLINT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     `TestId` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL',
--     `TestDesc` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL' COMMENT 'C\\0f4ng th\\u1ee9c m\\0e1u...',
--     `TestType` ENUM('XN', 'CDHA', 'TDCN') NULL DEFAULT 'DEFAULT NULL',
--     `TestSystem` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Sinh h\\0f3a...'
-- );
-- ALTER TABLE
--     `ListTest` ADD UNIQUE `listtest_testid_unique`(`TestId`);
-- CREATE TABLE `Visit`(
--     `VisitId` BIGINT(20) NULL DEFAULT 'DEFAULT NULL',
--     `EmrId` INT(10) UNSIGNED NULL DEFAULT 'DEFAULT NULL',
--     `VisitType` ENUM(
--         'Nh\u1eadn b\u1ec7nh',
--         'B\u1ec7nh \0e1n',
--         'Th\u01b0\u1eddng quy',
--         '\u0110\u1ed9t xu\u1ea5t',
--         'H\u1ed9i ch\u1ea9n',
--         'Xu\u1ea5t vi\u1ec7n',
--         'T\0e1i kh\0e1m'
--     ) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Lo\\u1ea1i c\\u1ee7a l\\u1ea7n th\\u0103m kh\\0e1m: b\\u1ec7nh \\0e1n ,  th\\u01b0\\u1eddng quy...',
--     `VisitTime` DATETIME NULL DEFAULT 'DEFAULT NULL',
--     `StaffId` SMALLINT(6) NULL DEFAULT 'DEFAULT NULL' COMMENT 'Nh\\0e2n vi\\0ean th\\u0103m kh\\0e1m ,  ch\\u1ec9 \\u0111\\u1ecbnh',
--     PRIMARY KEY(`VisitId`)
-- );
-- ALTER TABLE
--     `Visit` ADD UNIQUE `visit_emrid_visitid_unique`(`EmrId`, `VisitId`);
-- ALTER TABLE
--     `Visit` ADD INDEX `visit_visitid_index`(`VisitId`);
-- ALTER TABLE
--     `Visit` ADD INDEX `visit_emrid_index`(`EmrId`);
-- ALTER TABLE
--     `Visit` ADD INDEX `visit_staffid_index`(`StaffId`);
-- CREATE TABLE `VisitDrug`(
--     `VisitId` BIGINT(20) NULL DEFAULT 'DEFAULT NULL',
--     `DrugId` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL',
--     `DrugRoute` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL',
--     `DrugQuantity` DOUBLE NULL DEFAULT 'DEFAULT NULL',
--     `DrugTimes` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL' COMMENT 'S\\u1ed1 l\\u1ea7n',
--     `DrugAtTime` DATETIME NULL DEFAULT 'DEFAULT NULL' COMMENT 'Th\\u1eddi \\u0111i\\u1ec3m d\\0f9ng',
--     `DrugNote` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL'
-- );
-- ALTER TABLE
--     `VisitDrug` ADD UNIQUE `visitdrug_drugid_visitid_unique`(`DrugId`, `VisitId`);
-- ALTER TABLE
--     `VisitDrug` ADD INDEX `visitdrug_visitid_index`(`VisitId`);
-- ALTER TABLE
--     `VisitDrug` ADD INDEX `visitdrug_visitid_index`(`VisitId`);
-- CREATE TABLE `VisitProcedure`(
--     `VisitId` BIGINT(20) NULL DEFAULT 'DEFAULT NULL',
--     `ProcedureId` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL'
-- );
-- ALTER TABLE
--     `VisitProcedure` ADD UNIQUE `visitprocedure_procedureid_visitid_unique`(`ProcedureId`, `VisitId`);
-- ALTER TABLE
--     `VisitProcedure` ADD INDEX `visitprocedure_visitid_index`(`VisitId`);
-- CREATE TABLE `VisitSign`(
--     `VisitId` BIGINT(20) NULL DEFAULT 'DEFAULT NULL',
--     `SignId` SMALLINT(6) NULL DEFAULT 'DEFAULT NULL',
--     `SignValue` ENUM(
--         'BT',
--         'C\0f3 DHBL',
--         'Kh\0f4ng',
--         '( +)',
--         '( ++)',
--         '( +++)',
--         '( +-)'
--     ) NULL DEFAULT 'DEFAULT NULL',
--     `FollowUp` TINYINT(1) NULL,
--     `ForEmr` TINYINT(1) NULL
-- );
-- ALTER TABLE
--     `VisitSign` ADD UNIQUE `visitsign_signid_visitid_unique`(`SignId`, `VisitId`);
-- ALTER TABLE
--     `VisitSign` ADD INDEX `visitsign_visitid_index`(`VisitId`);
-- CREATE TABLE `VisitTest`(
--     `VisitId` BIGINT(20) NULL DEFAULT 'DEFAULT NULL',
--     `TestId` VARCHAR(50) NULL DEFAULT 'DEFAULT NULL',
--     `TestResult` VARCHAR(255) NULL DEFAULT 'DEFAULT NULL'
-- );
-- ALTER TABLE
--     `VisitTest` ADD UNIQUE `visittest_testid_visitid_unique`(`TestId`, `VisitId`);
-- ALTER TABLE
--     `VisitTest` ADD INDEX `visittest_visitid_index`(`VisitId`);
-- ALTER TABLE
--     `VisitDrug` ADD CONSTRAINT `visitdrug_drugid_foreign` FOREIGN KEY(`DrugId`) REFERENCES `ListDrug`(`DrugId`);
-- ALTER TABLE
--     `VisitProcedure` ADD CONSTRAINT `visitprocedure_visitid_foreign` FOREIGN KEY(`VisitId`) REFERENCES `Visit`(`VisitId`);
-- ALTER TABLE
--     `VisitProcedure` ADD CONSTRAINT `visitprocedure_procedureid_foreign` FOREIGN KEY(`ProcedureId`) REFERENCES `ListProcedure`(`ProcedureId`);
-- ALTER TABLE
--     `ListSign` ADD CONSTRAINT `listsign_emrsampleid_foreign` FOREIGN KEY(`EmrSampleId`) REFERENCES `EmrSample`(`EmrSampleId`);
-- ALTER TABLE
--     `VisitSign` ADD CONSTRAINT `visitsign_signid_foreign` FOREIGN KEY(`SignId`) REFERENCES `ListSign`(`SignId`);
-- ALTER TABLE
--     `VisitSign` ADD CONSTRAINT `visitsign_visitid_foreign` FOREIGN KEY(`VisitId`) REFERENCES `Visit`(`VisitId`);
-- ALTER TABLE
--     `ListStaff` ADD CONSTRAINT `liststaff_derpartmentid_foreign` FOREIGN KEY(`DerpartmentId`) REFERENCES `ListDepartment`(`DepartmentId`);
-- ALTER TABLE
--     `VisitTest` ADD CONSTRAINT `visittest_testid_foreign` FOREIGN KEY(`TestId`) REFERENCES `ListTest`(`TestId`);
-- ALTER TABLE
--     `Visit` ADD CONSTRAINT `visit_emrid_foreign` FOREIGN KEY(`EmrId`) REFERENCES `EmrAdmission`(`EmrId`);
-- ALTER TABLE
--     `VisitDrug` ADD CONSTRAINT `visitdrug_visitid_foreign` FOREIGN KEY(`VisitId`) REFERENCES `Visit`(`VisitId`);
-- ALTER TABLE
--     `Visit` ADD CONSTRAINT `visit_staffid_foreign` FOREIGN KEY(`StaffId`) REFERENCES `ListStaff`(`StaffId`);
-- ALTER TABLE
--     `EmrAdmission` ADD CONSTRAINT `emradmission_departmentid_foreign` FOREIGN KEY(`DepartmentId`) REFERENCES `ListDepartment`(`DepartmentId`);
-- ALTER TABLE
--     `VisitTest` ADD CONSTRAINT `visittest_visitid_foreign` FOREIGN KEY(`VisitId`) REFERENCES `Visit`(`VisitId`);